local heraTypes = {};

export type heraCurveCreateInfo = {
	name : string;
};

export type heraCurveBinCreateInfo = {
	name : string;
};

export type heraCurveHandleCreateInfo = {
	name : string;
};

export type heraEnvironmentCreateInfo = {
	name : string;
};

export type heraFileCreateInfo = {
	name : string;
};

export type heraKeyframeCreateInfo = {
	name : string;
};

export type heraPortCreateInfo = {
	name : string;
};

export type heraSequenceCreateInfo = {
	name : string;
};

export type heraTimelineCreateInfo = {
	name : string;
};

export type heraTransitCreateInfo = {
	name : string;
};

return heraTypes;